openapi: 3.0.0
info:
  title: RAG Agent API
  description: API for connecting frontend to backend RAG agent
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Local development server
  - url: https://api.example.com
    description: Production server

paths:
  /rag-agent/query:
    post:
      summary: Process a user query through the RAG agent
      description: Sends a user query to the RAG agent and returns a grounded response based on book content with source citations and links
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserQuery'
      responses:
        '200':
          description: Successful response from the RAG agent with source citations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RAGResponse'
        '400':
          description: Invalid request parameters (e.g., query exceeds character limit)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /rag-agent/health:
    get:
      summary: Check the health status of the RAG agent
      description: Returns the health status of the RAG agent service
      responses:
        '200':
          description: RAG agent is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

components:
  schemas:
    UserQuery:
      type: object
      required:
        - query_text
      properties:
        query_text:
          type: string
          description: The user's query text (500-1000 character limit)
          example: "What is artificial intelligence?"
          maxLength: 1000
          minLength: 1
        selected_text:
          type: string
          description: Optional selected text from the book content (included as context in the query)
          example: "Artificial intelligence is a branch of computer science..."
          maxLength: 5000
        top_k:
          type: integer
          description: Number of results to retrieve (default 5)
          default: 5
          minimum: 1
          maximum: 20
        include_citations:
          type: boolean
          description: Whether to include source citations and links in the response
          default: true

    RAGResponse:
      type: object
      required:
        - query_text
        - answer
        - retrieved_chunks
        - confidence_score
        - execution_time
        - timestamp
      properties:
        query_text:
          type: string
          description: The original query text
          example: "What is artificial intelligence?"
        answer:
          type: string
          description: The generated answer to the query with source citations
          example: "Artificial intelligence (AI) is intelligence demonstrated by machines..."
        retrieved_chunks:
          type: array
          items:
            $ref: '#/components/schemas/ContentChunk'
          description: Content chunks retrieved from the vector database with source citations and links
        confidence_score:
          type: number
          format: float
          description: Overall confidence in the answer (0.0 to 1.0)
          minimum: 0.0
          maximum: 1.0
          example: 0.85
        execution_time:
          type: number
          format: float
          description: Time taken to generate the response in seconds
          example: 2.45
        timestamp:
          type: string
          format: date-time
          description: When the response was generated
          example: "2025-12-16T10:30:00Z"

    ContentChunk:
      type: object
      required:
        - content
        - similarity_score
        - metadata
        - rank
      properties:
        content:
          type: string
          description: The text content of the chunk
          example: "Artificial intelligence (AI) is intelligence demonstrated by machines..."
        similarity_score:
          type: number
          format: float
          description: How similar this chunk is to the query (0.0 to 1.0)
          minimum: 0.0
          maximum: 1.0
          example: 0.92
        metadata:
          $ref: '#/components/schemas/ContentMetadata'
        rank:
          type: integer
          description: The rank of this chunk in the results (1 is most relevant)
          example: 1

    ContentMetadata:
      type: object
      required:
        - url
        - title
      properties:
        url:
          type: string
          description: URL where this content originated (for source citation links)
          example: "https://ai-book.example.com/chapter-1"
        title:
          type: string
          description: Title of the source document
          example: "Introduction to Artificial Intelligence"
        chunk_index:
          type: integer
          description: Position of this chunk in the original document
          example: 3
        source_metadata:
          type: object
          description: Additional metadata about the source
          example: {"author": "John Doe", "section": "1.1"}

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
          example: "QUERY_PROCESSING_ERROR"
        message:
          type: string
          description: Human-readable error message with option to retry
          example: "Failed to process query due to internal error. Please try again."

    HealthResponse:
      type: object
      required:
        - status
        - timestamp
      properties:
        status:
          type: string
          description: Health status of the service
          enum: [healthy, degraded, unavailable]
          example: "healthy"
        timestamp:
          type: string
          format: date-time
          description: When the health check was performed
          example: "2025-12-16T10:30:00Z"
        details:
          type: object
          description: Additional health details
          example: {"qdrant_connected": true, "model_loaded": true}