openapi: 3.0.0
info:
  title: Better-Auth API
  description: API for user authentication and profile management
  version: 1.0.0
paths:
  /api/auth/signup:
    post:
      summary: Register a new user
      description: Creates a new user account with experience levels
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - software_experience
                - hardware_experience
              properties:
                email:
                  type: string
                  format: email
                  example: "user@example.com"
                password:
                  type: string
                  format: password
                  example: "securePassword123"
                software_experience:
                  type: string
                  enum: [beginner, intermediate, advanced]
                  example: "beginner"
                hardware_experience:
                  type: string
                  enum: [none, basic, advanced]
                  example: "none"
      responses:
        '200':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User registered successfully"
                  profile_id:
                    type: integer
                    example: 1
                  user_id:
                    type: string
                    example: "user-123"
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Conflict - user already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/auth/signin:
    post:
      summary: Authenticate a user
      description: Authenticates a user and returns session information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: "user@example.com"
                password:
                  type: string
                  format: password
                  example: "securePassword123"
      responses:
        '200':
          description: User authenticated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User authenticated successfully"
                  email:
                    type: string
                    format: email
                    example: "user@example.com"
                  user_id:
                    type: string
                    example: "user-123"
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/auth/profile:
    get:
      summary: Retrieve user profile
      description: Gets the user's profile information for personalization
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: string
            format: email
      responses:
        '200':
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '400':
          description: Bad request - missing email parameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: User profile not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      summary: Update user profile
      description: Updates the user's profile information
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: string
            format: email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                software_experience:
                  type: string
                  enum: [beginner, intermediate, advanced]
                hardware_experience:
                  type: string
                  enum: [none, basic, advanced]
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Profile updated successfully"
                  profile_id:
                    type: integer
                    example: 1
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: User profile not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /health:
    get:
      summary: Health check
      description: Check if the API is running
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"

components:
  schemas:
    UserProfile:
      type: object
      properties:
        id:
          type: integer
          example: 1
        user_id:
          type: string
          example: "user-123"
        email:
          type: string
          format: email
          example: "user@example.com"
        software_experience:
          type: string
          enum: [beginner, intermediate, advanced]
          example: "beginner"
        hardware_experience:
          type: string
          enum: [none, basic, advanced]
          example: "none"
    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
          example: "Error message describing the issue"